spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
    url: jdbc:h2:mem:jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false

  output.ansi: enabled=always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: true
  thymeleaf:
    cache: false

logging:
  pattern:
#    console: '%(%d{yyyy-MM-dd HH:mm:ss} [%t] %clr(%30.30logger:%-4line){cyan}) %clr(%-5level) > %msg\n'
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace